import jsPDF from 'jspdf'

export type VisitServiceLine = {
  name: string
  quantity: number
  unit_price_egp: number
}

export type ServicesInvoicePatient = {
  full_name: string
  phone: string | null
  display_id: string | null
}

export type ServicesInvoiceClinic = {
  name: string
  address: string | null
  contact_phone: string | null
  contact_email: string | null
  owner_full_name: string | null
}

export function generateServicesInvoicePDF(params: {
  patient: ServicesInvoicePatient
  clinic: ServicesInvoiceClinic
  items: VisitServiceLine[]
  invoiceNumber: string
  date: string
  isAr: boolean
}): jsPDF {
  const { patient, clinic, items, invoiceNumber, date, isAr } = params
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  const total = items.reduce((sum, it) => sum + it.quantity * it.unit_price_egp, 0)

  let y = 20

  // Header bar
  doc.setFillColor(15, 23, 42)
  doc.rect(0, 0, pageWidth, 35, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(clinic.name, 15, 15)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(isAr ? 'فاتورة خدمات' : 'SERVICES INVOICE', pageWidth - 15, 15, { align: 'right' })

  doc.setFontSize(8)
  doc.text(`${isAr ? 'رقم الفاتورة' : 'Invoice #'}: ${invoiceNumber}`, pageWidth - 15, 22, { align: 'right' })

  const dateStr = new Date(date).toLocaleDateString(isAr ? 'ar-EG' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  doc.text(`${isAr ? 'التاريخ' : 'Date'}: ${dateStr}`, pageWidth - 15, 29, { align: 'right' })

  y = 45

  // Clinic details (left) & patient details (right)
  doc.setTextColor(100, 116, 139)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.text(isAr ? 'العيادة' : 'FROM', 15, y)
  doc.setFont('helvetica', 'normal')
  doc.text(isAr ? 'المريض' : 'BILL TO', pageWidth - 15, y, { align: 'right' })

  y += 6
  doc.setFontSize(9)
  doc.setTextColor(30, 41, 59)

  const clinicLines: string[] = [
    clinic.name,
    clinic.address || '',
    clinic.contact_phone || '',
    clinic.contact_email || '',
  ].filter(Boolean)

  const patientLines: string[] = [
    patient.full_name,
    patient.phone || '',
    patient.display_id ? `${isAr ? 'رقم المريض' : 'Patient #'}: ${patient.display_id}` : '',
  ].filter(Boolean)

  const maxLines = Math.max(clinicLines.length, patientLines.length)
  for (let i = 0; i < maxLines; i++) {
    if (clinicLines[i]) doc.text(clinicLines[i], 15, y + i * 5)
    if (patientLines[i]) doc.text(patientLines[i], pageWidth - 15, y + i * 5, { align: 'right' })
  }

  y += maxLines * 5 + 8

  // Divider
  doc.setDrawColor(226, 232, 240)
  doc.line(15, y, pageWidth - 15, y)
  y += 10

  // Services table header
  doc.setFillColor(241, 245, 249)
  doc.rect(15, y - 4, pageWidth - 30, 8, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(71, 85, 105)
  doc.text(isAr ? 'الخدمة' : 'Service', 18, y + 1)
  doc.text(isAr ? 'الكمية' : 'Qty', pageWidth / 2 - 20, y + 1, { align: 'center' })
  doc.text(isAr ? 'السعر' : 'Unit Price', pageWidth / 2 + 20, y + 1, { align: 'center' })
  doc.text(isAr ? 'الإجمالي' : 'Total', pageWidth - 18, y + 1, { align: 'right' })
  y += 10

  // Services
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  for (const item of items) {
    if (y > 270) {
      doc.addPage()
      y = 20
    }
    doc.setTextColor(30, 41, 59)
    const name = item.name.length > 40 ? `${item.name.slice(0, 37)}...` : item.name
    doc.text(name, 18, y)
    doc.text(String(item.quantity), pageWidth / 2 - 20, y, { align: 'center' })
    doc.text(`${item.unit_price_egp.toLocaleString()} EGP`, pageWidth / 2 + 20, y, { align: 'center' })
    doc.text(`${(item.quantity * item.unit_price_egp).toLocaleString()} EGP`, pageWidth - 18, y, { align: 'right' })
    y += 6
  }

  y += 4

  // Divider
  doc.setDrawColor(226, 232, 240)
  doc.line(15, y, pageWidth - 15, y)
  y += 8

  // Total
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.setFont('helvetica', 'normal')
  doc.text(isAr ? 'الإجمالي' : 'Total', 15, y)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(15, 23, 42)
  doc.text(`${total.toLocaleString()} EGP`, pageWidth - 15, y, { align: 'right' })
  y += 12

  if (clinic.owner_full_name) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(71, 85, 105)
    doc.text(isAr ? `تم الإعداد بواسطة: ${clinic.owner_full_name}` : `Prepared by: ${clinic.owner_full_name}`, 15, y)
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15
  doc.setFontSize(7)
  doc.setTextColor(148, 163, 184)
  doc.text(
    isAr ? 'تم إنشاء هذه الفاتورة بواسطة ClinicOS' : 'Generated by ClinicOS',
    pageWidth / 2,
    footerY,
    { align: 'center' }
  )

  return doc
}
